### ISSUE TITLE
no max width set

### ISSUE THREAD

**Issue by unknowndevice** [necrosoftgames/differently#2]
This is pretty annoying on larger screens so I've set the max width to 1400px;

```css
html {
  margin: 0px auto;
  max-width: 1400px;
}
```

Thanks for pointing this out! https://twitter.com/Crowbeak/status/558236031640551424
